### ISSUE TITLE
node_modules nicht committen!

### ISSUE THREAD

**Issue by L3P3** [LFF5644/MusikPlayer#1]
Erstell mal eine Datei .gitignore und schreib da node_modules rein! Und vorher den Ordner löschen und committen. node_modules ist Geräteabhängig, redundant (da npm install das von selbst macht) und macht Sachen unnötig größer. WEG DAMIT :gun:

**Comment by LFF5644** [comment]
was macht .gitignore ?

**Comment by LFF5644** [comment]
so hab ich

aber es ändert sich nichts

**Comment by L3P3** [comment]
"vorher den Ordner löschen und committen"

Lies richtig!

**Comment by LFF5644** [comment]
SICHT SO FRECH!

**Comment by L3P3** [comment]
NICHT FRECH :x:

**Comment by L3P3** [comment]
Los, eröffne des Issue neu, du hast es nicht gelöst!
